# Practice on NumPy and pandas

Here are some task for you, to refresh what you saw in the notebooks before.

It will help you strengthen the **learning objectives** from the notebook before. You should be able to
- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays


## Part 1: Creating NumPy arrays.

1. Please create a NumPy array from the list:
```Python
my_list = [1, 2, 5, 6, 8]
````

- Please create a numpy array containing the values from 1 to 10.
-  Please create a numpy array from 0 to 5 with a step size of 0.2
- Create a numpy array with the shape 2,3 with random values


2. Please create a NumPy array containing the values from 1 to 10.


In [77]:
import numpy as np
array1 = np.arange(1,11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

3. Please create a NumPy array from 0 to 5 with a step size of 0.2


In [78]:
array2 = np.arange(0,6,0.2)
array2

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8])

4. Create a NumPy array with the shape 2,3 with random values


In [79]:
array3 = np.random.rand(2,3)
array3

array([[0.89834731, 0.81305537, 0.99961223],
       [0.1480193 , 0.31368788, 0.08045601]])

## Part 2: Manipulate NumPy arrays.

1. Please create a NumPy array with (1, 3, '4', 7, 12, '0'). Define the content as integer.


In [80]:
array4 = np.array([1,3,'4',7,12,'0'],np.int32)
array4

array([ 1,  3,  4,  7, 12,  0], dtype=int32)

2. Check the data type of the objects and the shape of the array


In [81]:
print(array4.dtype)
print(array4.shape)

int32
(6,)


3. Update the 4th value to 30.


In [82]:
array4[3] = 30
array4

array([ 1,  3,  4, 30, 12,  0], dtype=int32)

4. Reshape the array to a 2x3 matrix.


In [83]:
array4 = array4.reshape(2,3)
array4

array([[ 1,  3,  4],
       [30, 12,  0]], dtype=int32)

5. Please add 8 to each value in the first row and 12 to each in the second row.


In [84]:
array4 = array4 + [[8],[12]]
array4

array([[ 9, 11, 12],
       [42, 24, 12]])

6. Multiply the first column with 2, the second with 3 and the third with 4.


In [85]:
array4 = array4 * [2,3,4]
array4

array([[18, 33, 48],
       [84, 72, 48]])

7. Please sum up all numbers in the first row, and all numbers in the second row.


In [ ]:
array4.sum(axis = 1)

array([ 99, 204])

8. Similarly, search for the largest number for each column.


In [93]:
array4.max(axis = 0)

array([84, 72, 48])

9. Extract the number in the second column and the first row.


In [102]:
print(array4[0,1]) #first row = index 0 | 2nd col = index 1
array4

33


array([[18, 33, 48],
       [84, 72, 48]])

10. Check at which index the value is exactly 48.

In [106]:
print(np.where(array4 == 48))
#first row, second row
#third column
print(np.where(array4 == 18))
#first row, first column

(array([0, 1]), array([2, 2]))
(array([0]), array([0]))
